import type { CommandContext, CommandResult } from '../types';
import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import chalk from 'chalk';

export interface ResearchApiOptions {
  target: string;
  depth?: 'quick' | 'deep' | 'forensic';
}

export class ResearchApiCommand {
  name = 'research-api';

  async execute(context: CommandContext, options: ResearchApiOptions): Promise<CommandResult> {
    try {
      const target = options.target;
      const depth = options.depth || 'deep';

      console.log(chalk.bold('\n=== API & Protocol Research ==='));
      console.log(chalk.cyan(`Target: ${target}`));
      console.log(chalk.cyan(`Depth: ${depth}\n`));

      // Step 1: Classify Target
      console.log(chalk.yellow('Step 1: Classifying target...'));
      const targetType = this.classifyTarget(target);
      console.log(chalk.green(`  ✓ Target type: ${targetType}\n`));

      // Step 2: Generate Research Plan
      console.log(chalk.yellow('Step 2: Generating research plan...'));
      const researchPlan = this.generateResearchPlan(target, targetType, depth);
      console.log(chalk.green('  ✓ Research plan generated\n'));

      // Step 3: Display Instructions
      console.log(chalk.bold('\n=== Research Instructions ===\n'));
      console.log(researchPlan);

      // Step 4: Create Research Document
      const docsDir = join(context.workDir, '.claude', 'docs', 'api-research');
      const targetName = this.sanitizeTargetName(target);
      const researchDocPath = join(docsDir, `${targetName}.md`);

      mkdirSync(docsDir, { recursive: true });

      const researchDoc = `# ${targetName} API Research

## Overview
- **Target**: ${target}
- **Type**: ${targetType}
- **Depth**: ${depth}
- **Date**: ${new Date().toISOString()}

## Research Plan

${researchPlan}

## Tools Used
- MCP grep (GitHub code search)
- Web Search (online research)
- Protocol analysis tools

## Findings
[Research results will be documented here]

## Endpoints Discovered
[Discovered endpoints]

## Authentication
[Auth mechanism documentation]

## Rate Limits
[Rate limiting information]

## Notes
[Additional notes and observations]

---
Generated by: komplete-kontrol-cli
`;

      writeFileSync(researchDocPath, researchDoc);

      console.log(chalk.gray(`\nResearch document saved to: ${researchDocPath}\n`));

      return {
        success: true,
        message: `Research plan generated for: ${target}`
      };
    } catch (error: any) {
      return {
        success: false,
        message: error.message || 'API research command failed'
      };
    }
  }

  private classifyTarget(target: string): string {
    if (target.startsWith('http://') || target.startsWith('https://')) {
      return 'REST API';
    }
    if (target.startsWith('grpc://') || target.includes('.proto')) {
      return 'gRPC/Protobuf';
    }
    if (target.includes('.apk')) {
      return 'Mobile (Android)';
    }
    if (target.includes('.app') || target.includes('.ipa')) {
      return 'Mobile (iOS/Android)';
    }
    if (target.includes('.dll') || target.includes('.so') || target.includes('.dylib')) {
      return 'Binary/Native';
    }
    if (target.endsWith('.crx') || target.endsWith('.js') || target.endsWith('.html')) {
      return 'Web Frontend';
    }
    return 'Unknown';
  }

  private generateResearchPlan(target: string, targetType: string, _depth: string): string {
    const plans: Record<string, string> = {
      'REST API': `
### For Web APIs:

1. **Traffic Capture**
   Start mitmproxy:
   \`\`\`bash
   mitmproxy -p 8080 -w capture.flow
   \`\`\`

2. **Endpoint Discovery**
   Use Kiterunner for shadow APIs:
   \`\`\`bash
   kr scan ${target} -w routes-large.kite -o results.json
   \`\`\`

3. **Schema Analysis**
   If OpenAPI available:
   \`\`\`bash
   schemathesis run ${target}/openapi.json
   \`\`\`

4. **Document Findings**
   - Endpoints discovered
   - Auth mechanism
   - Rate limits
   - Required headers
`,
      'GraphQL': `
### For GraphQL:

1. **Introspection Check**
   \`\`\`graphql
   {
     __schema {
       types { name fields { name type { name } } }
     }
   }
   \`\`\`

2. **If Introspection Disabled**
   Use Clairvoyance:
   \`\`\`bash
   python clairvoyance.py -t ${target} -w wordlist.txt -o schema.json
   \`\`\`

3. **Schema Reconstruction**
   - Types discovered
   - Mutations available
   - Queries available
`,
      'gRPC/Protobuf': `
### For Binary Protocols:

1. **Protocol Identification**
   \`\`\`bash
   cat response.bin | protoc --decode_raw
   \`\`\`

2. **Schema Recovery**
   From APK:
   \`\`\`bash
   pbtk extract app.apk -o protos/
   \`\`\`

3. **Documentation**
   - Message types
   - Field mappings
   - Service definitions
`,
      'Mobile (Android)': `
### For Mobile Apps:

1. **APK Analysis**
   \`\`\`bash
   jadx -d output/ app.apk
   \`\`\`

2. **Runtime Interception**
   SSL Pinning Bypass:
   \`\`\`bash
   objection -g "App Name" explore --startup-command "android sslpinning disable"
   \`\`\`

3. **Traffic Analysis**
   - Base URL
   - Auth flow
   - Interesting endpoints
`,
      'Mobile (iOS/Android)': `
### For Mobile Apps:

1. **APK Analysis**
   \`\`\`bash
   jadx -d output/ app.apk
   \`\`\`

2. **Runtime Interception**
   SSL Pinning Bypass:
   \`\`\`bash
   objection -g "App Name" explore --startup-command "android sslpinning disable"
   \`\`\`

3. **Traffic Analysis**
   - Base URL
   - Auth flow
   - Interesting endpoints
`,
      'Binary/Native': `
### For Binary Protocols:

1. **Protocol Identification**
   \`\`\`bash
   cat response.bin | protoc --decode_raw
   \`\`\`

2. **Schema Recovery**
   From APK:
   \`\`\`bash
   pbtk extract app.apk -o protos/
   \`\`\`

3. **Documentation**
   - Message types
   - Field mappings
   - Service definitions
`,
      'Web Frontend': `
### For Web Frontend:

1. **Code Analysis**
   - Analyze JavaScript/TypeScript
   - Check for minification
   - Identify frameworks

2. **Traffic Capture**
   - Use browser DevTools
   - Check network tab
   - Analyze API calls

3. **Source Map Recovery**
   - Check for .map files
   - Use source map explorers
`,
      'Unknown': `
### For Unknown Targets:

1. **Manual Analysis**
   - Read file contents
   - Identify patterns
   - Search for clues

2. **Tool Selection**
   - Try multiple tools
   - Cross-reference findings

3. **Documentation**
   - Document all discoveries
   - Note unknown elements
`
    };

    return plans[targetType] || plans['Unknown'];
  }

  private sanitizeTargetName(target: string): string {
    return target
      .replace(/[^a-zA-Z0-9-]/g, '_')
      .substring(0, 50);
  }
}
